### PR TITLE
Added error messages (and config.php)

### PR DESCRIPTION
**Pull request by Mikescher**
Hey,

I was confused on my server if the cpu load was queried correctly or if it showed 0 because of an error (turns out it really was avg zero over the last 15minutes).

So I added error messages that get displayed when commands fail:

To do this I moved quite a bit of your code around, I hope that was ok :D.
- All system information gathering is now in methods in system.php
- The file swmp.php is pretty much only calling these functions
- The few extra functions from mainclass.php are now in utils.php as normal methods (getHumanTime, getSize, etc)
- I removed a bit of the json_encode decode stuff, some values where two times encoded and then in js again decoded. But JSON is already valid javascript (the JS stands for javascript :D) so you can directly print them into the js code.

I also added a config.php / config.local.php where it is possible to disable the shown errors and set the theme. This is useful when the code is automatically updated via git, because otherwise the theme changes in index.php will always get overriden (this ways `config.local.php` is not in the git repo and does not get overriden).

Thats quite a cool project, if you have any problems with my changes just say it - perhaps I can do it better/different.

Greets
 ~ Mike

PS: Perhaps wait with merging until tommorrow, I want to test my changes a bit more but for today it's too late for me :)

### CODE REVIEW

**Comment by fuzzymannerz** [comment]
Hey @Mikescher!
This is awesome! I did think about implementing some sort of error display but didn't get round to it, I even started making a configuration file and gave up after some hurdles so the fact that you have done both is nice! haha

However, this was submitted the other day and I don't know the situation with it so I can't just merge yours without taking into consideration others major code changes also.
https://github.com/fuzzymannerz/swmp/issues/3 - @daison12006013 

The two code changes of both you guys would most likely conflict with each other so maybe you could work something out with what you both have already? :)

**Comment by daison12006013** [comment]
Hey @Mikescher, please sync merge the updates buddy and maybe fix the updates I did.

@fuzzymannerz, buddy, you don't need to close an issue or PR automatically, we should mostly close those if not necessary, this PR can still fix by @Mikescher once he applied a merge to the master itself.

**Comment by fuzzymannerz** [comment]
@daison12006013 Very good point! re-opened. :+1:

**Comment by Mikescher** [comment]
Okay, stuff is merged and everything seems ok.

From my POV it's ready to be merged.

@daison12006013: I didn't go all the way to pack the methods in a single class and only moved them to a single file (and put all the functionality in methods in the first case). But I think if you go on and refactored it into classes (#3) that shouldn't be too hard and would improve the overall readability :D

**Comment by fuzzymannerz** [comment]
@Mikescher Nice one man! :grinning:

**Pull request merged**
